### ISSUE TITLE
Conflict between spring-boot-starter-web and spring-grpc-spring-boot-starter causes application startup failure

### ISSUE THREAD

**Issue by davidchoi23** [spring-projects-experimental/spring-grpc#83] opened 2024-12-19 20:46 UTC
Hello Spring GRPC Team,

I encountered an issue when using spring-boot-starter-web and spring-grpc-spring-boot-starter together in a Spring Boot project. The application fails to start due to a conflict between the two dependencies.

Steps to Reproduce
1. Create a Spring Boot project with the following dependencies:

- spring-boot-starter-web
- spring-grpc-spring-boot-starter:0.3.0-SNAPSHOT

2. Configure the application with a minimal setup.
3. Attempt to start the application using ./gradlew bootRun.

Expected Behavior

The application should start successfully and both web and GRPC servers should work seamlessly.

Actual Behavior

The application fails to start with the following error:

```

java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.task.TaskExecutorConfigurations$ThreadPoolTaskExecutorBuilderConfiguration.threadPoolTaskExecutorBuilder
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:99) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:184) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:121) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:430) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:290) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:791) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:609) ~[spring-context-6.2.1.jar:6.2.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.4.1.jar:3.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-3.4.1.jar:3.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.4.1.jar:3.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.4.1.jar:3.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361) ~[spring-boot-3.4.1.jar:3.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350) ~[spring-boot-3.4.1.jar:3.4.1]
	at com.example.test_grpc_web.TestGrpcWebApplication.main(TestGrpcWebApplication.java:10) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.4.1.jar:3.4.1]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.grpc.autoconfigure.server.GrpcServerFactoryAutoConfiguration$GrpcServletConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@5a07e868]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:751) ~[spring-beans-6.2.1.jar:6.2.1]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1745) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:750) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:683) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:654) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1683) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:592) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:564) ~[spring-beans-6.2.1.jar:6.2.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanDefinitionsForType(OnBeanCondition.java:332) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanDefinitionsForType(OnBeanCondition.java:324) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanDefinitionsForType(OnBeanCondition.java:314) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:213) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.evaluateConditionalOnMissingBean(OnBeanCondition.java:196) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:143) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-3.4.1.jar:3.4.1]
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/grpc/servlet/jakarta/ServletServerBuilder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3650) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2735) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.2.1.jar:6.2.1]
	... 37 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.grpc.servlet.jakarta.ServletServerBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[na:na]
	... 41 common frames omitted

```

This error seems to be caused by spring-boot-starter-web initializing the default servlet stack while spring-grpc-spring-boot-starter tries to configure a GRPC Servlet server.

Environment
	•	Spring Boot Version: 3.4.1
	•	Spring GRPC Version: 0.3.0-SNAPSHOT
	•	Java Version: 23.0.1
	•	Dependencies:
	•	spring-boot-starter-web
	•	spring-grpc-spring-boot-starter:0.3.0-SNAPSHOT

Additional Notes
	•	The issue persists even when aligning GRPC dependencies to the same version (e.g., 1.56.0 for grpc-netty, grpc-services, and grpc-servlet).
	•	Excluding spring-boot-starter-web or grpc-servlet avoids the issue but disables either web or GRPC functionality.

Could you please confirm if this is a known issue or provide guidance on how to properly configure spring-boot-starter-web and spring-grpc-spring-boot-starter together in a single application?

Thank you for your help!. 😊

**Comment by onobc** [comment] 2024-12-19 23:42
Hi @davidchoi23 ,

Thanks for the report. And yes, this should work. 
Looks like we need to add some more guards on the auto-configuration as it currently assumes that the `io.grpc:grpc-servlet-jakarta' is on the classpath.

## Workaround
Add this dependency to your `build.gradle`:
```groovy
implementation 'io.grpc:grpc-servlet-jakarta'
```
We will get this fixed in the product as well.

**Comment by onobc** [comment] 2024-12-20 00:15
I reproduced the issue and have done the following:

1) add a guard to GrpcServlet on the AC
2) add tests for this case
3) update docs about having to add the `io.grpc:grpc-servlet-jakarta` dep

I can see long-term this could be some variant of grpc starter that includes servlet support. For now just adding the dependency in the generated `build.gradle` would do the trick. @dsyer @mhalbritter wdyt?

**Comment by spencergibb** [comment] 2024-12-20 00:27
Seems like two starters, webmvc and webflux

**Comment by davidchoi23** [comment] 2024-12-20 03:02
I encountered an issue while using io.grpc:grpc-servlet-jakarta in a Spring Boot application with both spring-boot-starter-web and spring-grpc-spring-boot-starter. After adding the grpc-servlet-jakarta dependency, the application starts successfully, but only the web service port is active. The GRPC port does not start.

<img width="608" alt="image" src="https://github.com/user-attachments/assets/d28f8ebf-3d8a-4ec2-882f-8d4dad993c22" />

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.4.0)

2024-12-20T11:59:59.542+09:00  INFO 5160 --- [demo] [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 21.0.5 with PID 5160 (/Users/david/workspace/demo/build/classes/java/main started by david in /Users/david/workspace/demo)
2024-12-20T11:59:59.543+09:00  INFO 5160 --- [demo] [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2024-12-20T11:59:59.892+09:00  INFO 5160 --- [demo] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-12-20T11:59:59.898+09:00  INFO 5160 --- [demo] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-12-20T11:59:59.898+09:00  INFO 5160 --- [demo] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.33]
2024-12-20T11:59:59.928+09:00  INFO 5160 --- [demo] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-12-20T11:59:59.928+09:00  INFO 5160 --- [demo] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 371 ms
2024-12-20T12:00:00.117+09:00  INFO 5160 --- [demo] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2024-12-20T12:00:00.121+09:00  INFO 5160 --- [demo] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.699 seconds (process running for 0.988)

```

**Comment by making** [comment] 2024-12-20 03:19
@davidchoi23 gRPC works on the same tomcat port (8080)

**Comment by davidchoi23** [comment] 2024-12-20 03:43
@making 
Despite explicitly setting the GRPC server port to 9090 using the spring.grpc.server.port property, the GRPC port does not activate.
<img width="331" alt="image" src="https://github.com/user-attachments/assets/84891f3a-acc9-47d7-830b-c5e37b9796b0" />

**Comment by davidchoi23** [comment] 2024-12-20 03:44
Am I setting the port incorrectly? Let me know if there are other alternatives.

**Comment by making** [comment] 2024-12-20 04:00
@davidchoi23 For the grpc request, use 8080 instead of 9090. With the Tomcat/Servlet integration, `spring.grpc.server.port` is not respected if I understand correctly.

**Closed** 2024-12-20 07:22 UTC
Labels: bug

**Comment by dsyer** [comment] 2024-12-23 15:05
Also in b3271be we added `spring.grpc.server.servlet.enabled=false` for people who want the servlet on the classpath but not to use it in the main MVC application.

**Comment by onobc** [comment] 2024-12-23 15:52
> Also in [b3271be](https://github.com/spring-projects-experimental/spring-grpc/commit/b3271be9188812acdb81470067d6bd01cd5d5fb3) we added `spring.grpc.server.servlet.enabled=false` for people who want the servlet on the classpath but not to use it in the main MVC application.

Nice one @dsyer . I was tempted to add this property in the previous PR as well.
